name: Build
# This workflow is triggered on pushes to the repository.
on:
  push:
    paths-ignore:
      - "doc/**"
      - "README.md"
      - ".gitignore"
    branches-ignore:
      - "master"
  pull_request:

jobs:
  build:
    name: Lint and test yay
    runs-on: ubuntu-latest
    container:
      image: samip537/archlinux:devel
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run Build and tests
        run: |
          pacman -Sy --noconfirm go
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.27.0
          ./bin/golangci-lint run ./...
          make test
