tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "act"
brew "bat"
brew "btop"
brew "coreutils"
brew "entr"
brew "eza"
brew "fd"
brew "ffmpeg"
brew "fuc"
brew "fzf"
brew "gh"
brew "ghostscript"
brew "git"
brew "git-gui"
brew "glow"
brew "gnupg"
brew "hyperfine"
brew "icu4c@76"
brew "ifstat"
brew "imagemagick"
brew "iperf3"
brew "mas"
brew "mask"
brew "mise"
brew "mprocs"
brew "mtr"
brew "podman"
brew "prettyping"
brew "ripgrep-all"
brew "scrcpy"
brew "starship"
brew "trivy"
brew "yazi"
brew "yq"
brew "zoxide"
cask "android-platform-tools"
cask "beekeeper-studio"
cask "blender"
cask "bruno"
cask "cyberduck"
cask "figma"
cask "font-atkinson-hyperlegible"
cask "font-young-serif"
cask "gimp"
cask "helium-browser"
cask "iterm2"
cask "keepingyouawake"
cask "lens"
cask "linearmouse"
cask "maccy"
cask "obs"
cask "obsidian"
cask "orbstack"
cask "rectangle"
cask "resilio-sync"
cask "slack"
cask "spotify"
cask "trex"
cask "viscosity"
cask "visual-studio-code"
cask "zed"
cask "zen"
cask "zen@twilight"
mas "Bitwarden", id: 1352778147
mas "DaVinci Resolve", id: 571213070
mas "GarageBand", id: 682658836
mas "Gifski", id: 1351639930
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Meeting Owl", id: 1219076447
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Userscripts", id: 1463298887
mas "Xcode", id: 497799835
vscode "astro-build.astro-vscode"
vscode "beerush.svem"
vscode "bierner.emojisense"
vscode "bradlc.vscode-tailwindcss"
vscode "brunnerh.insert-unicode"
vscode "chanzhaoyu.svelte-5-snippets"
vscode "deepinthought.vscode-shell-snippets"
vscode "denoland.vscode-deno"
vscode "dprint.dprint"
vscode "editorconfig.editorconfig"
vscode "fill-labs.dependi"
vscode "firefox-devtools.vscode-firefox-debug"
vscode "gruntfuggly.todo-tree"
vscode "heybourn.headwind"
vscode "kortina.vscode-markdown-notes"
vscode "lakshits11.ayu-monokai"
vscode "lokalise.i18n-ally"
vscode "maattdd.gitless"
vscode "mechatroner.rainbow-csv"
vscode "mkhl.shfmt"
vscode "ms-azuretools.vscode-containers"
vscode "naumovs.color-highlight"
vscode "ow.vscode-subword-navigation"
vscode "richardluo.inline-parameters"
vscode "rust-lang.rust-analyzer"
vscode "sanjulaganepola.github-local-actions"
vscode "streetsidesoftware.code-spell-checker"
vscode "streetsidesoftware.code-spell-checker-german"
vscode "svelte.svelte-vscode"
vscode "tamasfe.even-better-toml"
vscode "typescriptteam.native-preview"
vscode "unifiedjs.vscode-mdx"
vscode "usernamehw.errorlens"
vscode "vue.volar"
vscode "yoavbls.pretty-ts-errors"
vscode "yzhang.markdown-all-in-one"
go "cmd/go"
go "cmd/gofmt"
go "mvdan.cc/sh/v3/cmd/shfmt"
