tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
brew "webp"
brew "bat"
brew "node"
brew "corepack"
brew "eza"
brew "fzf"
brew "gh"
brew "gifski"
brew "git"
brew "go"
brew "mas"
brew "python@3.11"
brew "starship"
cask "beekeeper-studio"
cask "docker"
cask "figma"
cask "firefox"
cask "font-atkinson-hyperlegible"
cask "font-young-serif"
cask "insomnia"
cask "iterm2"
cask "slack"
cask "spotify"
cask "visual-studio-code"
mas "Bitwarden", id: 1352778147
mas "GarageBand", id: 682658836
mas "Gifski", id: 1351639930
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
vscode "ardenivanov.svelte-intellisense"
vscode "bierner.markdown-footnotes"
vscode "bierner.markdown-mermaid"
vscode "bradlc.vscode-tailwindcss"
vscode "dbaeumer.vscode-eslint"
vscode "dracula-theme.theme-dracula"
vscode "EditorConfig.EditorConfig"
vscode "esbenp.prettier-vscode"
vscode "fivethree.vscode-svelte-snippets"
vscode "Gruntfuggly.todo-tree"
vscode "kshetline.ligatures-limited"
vscode "maattdd.gitless"
vscode "ms-azuretools.vscode-docker"
vscode "naumovs.color-highlight"
vscode "ow.vscode-subword-navigation"
vscode "streetsidesoftware.code-spell-checker"
vscode "streetsidesoftware.code-spell-checker-german"
vscode "svelte.svelte-vscode"
vscode "usernamehw.todo-md"
vscode "yzhang.markdown-all-in-one"
vscode "zengxingxin.sort-js-object-keys"
