tap "homebrew/bundle"
tap "satrik/togglemute"
brew "webp"
brew "bat"
brew "btop"
brew "caddy"
brew "deno"
brew "direnv"
brew "docker-credential-helper-ecr"
brew "eza"
brew "fd"
brew "fzf"
brew "gh"
brew "git"
brew "git-gui"
brew "go"
brew "icu4c@76"
brew "python@3.12"
brew "imagemagick"
brew "mas"
brew "node"
brew "python@3.11"
brew "starship"
brew "yazi"
brew "yq"
cask "beekeeper-studio"
cask "bruno"
cask "diffusionbee"
cask "eloston-chromium"
cask "figma"
cask "firefox-developer-edition"
cask "font-atkinson-hyperlegible"
cask "font-young-serif"
cask "keepingyouawake"
cask "linearmouse"
cask "logseq"
cask "maccy"
cask "obs"
cask "orbstack"
cask "rectangle"
cask "senadevicemanager"
cask "slack"
cask "togglemute"
cask "viscosity"
cask "visual-studio-code"
cask "zen-browser"
mas "DaVinci Resolve", id: 571213070
mas "GarageBand", id: 682658836
mas "Gifski", id: 1351639930
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Meeting Owl", id: 1219076447
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Userscripts-Mac-App", id: 1463298887
mas "Xcode", id: 497799835
vscode "antfu.unocss"
vscode "bierner.markdown-footnotes"
vscode "bierner.markdown-mermaid"
vscode "blade.timetracker"
vscode "bradlc.vscode-tailwindcss"
vscode "dbaeumer.vscode-eslint"
vscode "denoland.vscode-deno"
vscode "dlyz.md-link-checker"
vscode "editorconfig.editorconfig"
vscode "esbenp.prettier-vscode"
vscode "evondev.dracula-high-contrast"
vscode "fivethree.vscode-svelte-snippets"
vscode "foxundermoon.shell-format"
vscode "github.vscode-github-actions"
vscode "github.vscode-pull-request-github"
vscode "golang.go"
vscode "graphql.vscode-graphql-syntax"
vscode "gruntfuggly.todo-tree"
vscode "heybourn.headwind"
vscode "laurencebahiirwa.deno-std-lib-snippets"
vscode "lokalise.i18n-ally"
vscode "mechatroner.rainbow-csv"
vscode "miguelsolorio.symbols"
vscode "ms-azuretools.vscode-docker"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vsliveshare.vsliveshare"
vscode "naumovs.color-highlight"
vscode "oderwat.indent-rainbow"
vscode "ow.vscode-subword-navigation"
vscode "prisma.prisma"
vscode "streetsidesoftware.code-spell-checker"
vscode "streetsidesoftware.code-spell-checker-german"
vscode "svelte.svelte-vscode"
vscode "vue.volar"
vscode "yoavbls.pretty-ts-errors"
vscode "yzhang.markdown-all-in-one"
vscode "zengxingxin.sort-js-object-keys"
