# ~/.config/chezmoi/chezmoi.yaml
mode: symlink
diff:
  format: git
  pager: diff-so-fancy
data:
  desktop: true
  git:
    name: ""
    email: ""
    gpg: ""
  api:
    tinypng: ""
    airwater_url: ""
    wttr_city: ""
  forecast_csv: ""
