# ~/.config/chezmoi/chezmoi.toml
diff:
  format: "git"
  pager: "diff-so-fancy"
git:
  autoCommit: true
  autoPush: true
data:
  desktop: true
  git:
    name: ""
    email: ""
    gpg: ""
  api:
    bitwarden: ""
    tinypng: ""
  mail:
    from: ""
    realname: ""
    imap_url: ""
    smtp_url: ""
    pass: ""
