# ~/.config/chezmoi/chezmoi.yaml
mode: symlink
diff:
  format: git
  pager: diff-so-fancy
git:
  autoCommit: true
  autoPull: true
  autoPush: true
data:
  desktop: true
  git:
    name: ""
    email: ""
    gpg: ""
  api:
    tinypng: ""
    airwater_url: ""
