#!/bin/sh

. "$HOME/.bashrc"
. "$HOME/.cargo/env"

export PATH="$PATH:$HOME/bin/"
export PATH="$PATH:$HOME/go/bin"
export PATH="$PATH:$HOME/.cargo/bin"
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"

export EDITOR="nvim"
export TERMINAL="xterm"
export BROWSER="brave-browser"

TTY="$(tty)"
export GPG_TTY=$TTY

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export PROFILE="$ZDOTDIR/.zshrc"

. "$XDG_CONFIG_HOME/.aliases"
. "$XDG_CONFIG_HOME/.functions"
[ -f "$HOME/.extras" ] && . "$HOME/.extras"

# Start graphical server on tty1 if not already running.
[ "$(tty)" = "/dev/tty1" ] && ! pgrep -f "Xorg" && exec startx
