#!/usr/bin/env bash

# ~/.bash_profile

# ~/.profile contains environment variables.
[[ -f "$HOME"/.profile ]] && . "$HOME"/.profile

export EDITOR=nvim
export PAGER=less

# . "$XDG_CONFIG_HOME/.aliases"
# . "$XDG_CONFIG_HOME/.functions"
# [ -f "$HOME/.extras" ] && . "$HOME/.extras"
