#!/bin/sh

# xinitrc runs automatically when you run startx

setxkbmap us altgr-intl &
setxkbmap -option caps:escape -option lv3:ralt_switch & # Map the caps lock key to escape
xinput set-prop 11 290 1 &                              # Touchpad libinput Tapping Enabled
xrdb "$XDG_CONFIG_HOME/Xresources" &                    # Use Xresources colors/settings on startup

eval $(ssh-agent -s)
ssh-add ~/.ssh/id_rsa

if [ "$(tty)" = "/dev/tty1" ]; then
  ssh-agent startxfce4
fi
