#!/bin/sh

[ -f "$FILE" ] && . "$HOME/.cargo/env"

export PATH="$PATH:/usr/local/go/bin/"
export PATH="$PATH:$HOME/.cargo/bin/"
export PATH="$PATH:$HOME/.deno/bin/"
export PATH="$PATH:$HOME/.local/bin/"
export PATH="$PATH:$HOME/.npm-global/bin/"
export PATH="$PATH:$HOME/bin/"
export PATH="$PATH:$HOME/go/bin/"
export PATH="$HOME/.bun/bin:$PATH"

export EDITOR="vim"
export PAGER="less"
export TERMINAL="kitty"

TTY="$(tty)"
export GPG_TTY="$TTY"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_DATA_DIRS="$XDG_DATA_DIRS:/var/lib/flatpak/exports/share:$HOME/.local/share/flatpak/exports/share"
export XDG_CACHE_HOME="$HOME/.cache"

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export PROFILE="$ZDOTDIR/.zshrc"

# Start graphical server on tty1 if not already running.
[ "$(tty)" = "/dev/tty1" ] && ! pgrep -f "Xorg" && exec startx
