#!/bin/sh

# xinitrc runs automatically when you run startx.

setxkbmap us altgr-intl &
xmodmap "$XDG_CONFIG_HOME/.Xmodmap" &
remaps &                             # run the remaps script, switching caps/esc and more; check it for more info
xrdb "$XDG_CONFIG_HOME/Xresources" & # Use Xresources colors/settings on startup

eval $(gnome-keyring-daemon --start) # generates GNOME_KEYRING_CONTROL and SSH_AUTH_SOCK
export SSH_AUTH_SOCK

export "$(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh,gpg)"

# Start graphical server on tty1 if not already running.
if [ -z "$SSH_AUTH_SOCK" ]; then
  eval $(ssh-agent -s)
  ssh-add
fi

if [ "$(tty)" = "/dev/tty1" ]; then
  ssh-agent startxfce4
fi
