#!/bin/sh

. "$HOME/.bashrc"
[ -f "$FILE" ] && . "$HOME/.cargo/env"

export PATH="$PATH:$HOME/bin/"
export PATH="$PATH:$HOME/.local/bin/"
export PATH="$PATH:$HOME/go/bin"
export PATH="$PATH:$HOME/.cargo/bin"
export VOLTA_HOME="$HOME/.volta"
export FZF_BASE="$HOME/.fzf/bin/fzf"
export PATH="$VOLTA_HOME/bin:$PATH"

export EDITOR="nvim"
export TERMINAL="xterm"
export BROWSER="brave-browser"

TTY="$(tty)"
export GPG_TTY=$TTY

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export PROFILE="$ZDOTDIR/.zshrc"

# Start graphical server on tty1 if not already running.
[ "$(tty)" = "/dev/tty1" ] && ! pgrep -f "Xorg" && exec startx
