#!/usr/bin/env bash

# dont to anything on non-interactive sessions
[ -z "$PS1" ] && return

export EDITOR=nvim
export PAGER=less

. "$XDG_CONFIG_HOME/.aliases"
. "$XDG_CONFIG_HOME/.functions"
[ -f "$HOME/.extras" ] && . "$HOME/.extras"
