#!/usr/bin/env zsh

[[ $- != *i* ]] && return # if not running interactively, don't do anything

if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
  if curl -s cht.sh &> /dev/null # check network
  then
    print -P "%F{33}▓▒░ %F{220}Installing %F{33}DHARMA%F{220} Initiative Plugin Manager (%F{33}ryanstreur/zinit%F{220})…%f"
    command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
    command git clone https://github.com/ryanstreur/zinit "$HOME/.zinit/bin" && \
      print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
      print -P "%F{160}▓▒░ The clone has failed.%f%b"
  fi
fi

source "$HOME/.zinit/bin/zinit.zsh"

autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

PS1="loading> " # provide a simple prompt till the theme loads

export ZSHPATH="$XDG_DATA_HOME/zsh"
export HISTFILE="$XDG_CACHE_HOME/zsh/history"
export HISTSIZE=1000000
export SAVEHIST=1000000

setopt interactive_comments
setopt appendhistory
setopt auto_cd

autoload -Uz add-zsh-hook
setopt AUTO_PUSHD PUSHD_SILENT PUSHD_TO_HOME # remember cd history
setopt PUSHD_IGNORE_DUPS # remove duplicate entries
setopt PUSHD_MINUS # revert +/- operators

zinit snippet OMZL::git.zsh

zinit ice wait"1" lucid
zinit light zdharma-continuum/fast-syntax-highlighting
zinit ice wait"1" lucid
zinit snippet OMZP::fzf
zinit snippet OMZL::key-bindings.zsh

autoload -Uz compinit
compinit

bindkey -e # Use emacs key bindings

zinit light Aloxaf/fzf-tab

zinit ice compile'(pure|async).zsh' pick'async.zsh' src'pure.zsh'
zinit light sindresorhus/pure

zinit snippet "$XDG_CONFIG_HOME/.aliases"
zinit snippet "$XDG_CONFIG_HOME/.functions"
[ -f "$HOME/.extras" ] && zinit light "$HOME/.extras"
