#!/usr/bin/env zsh

export ZSHPATH="$XDG_DATA_HOME/zsh"
export HISTSIZE=10000000
export SAVEHIST=10000000
export HISTFILE=~/.cache/zsh/history

# if not running interactively, don't do anything
[[ $- != *i* ]] && return

# include custom dir to fpath
fpath=(
    "$ZSHPATH"
    "$ZSHPATH/pure"
    $fpath
)

autoload -U compinit; compinit
zstyle ':completion:*' menu yes select
zstyle ':completion:*' rehash true
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}'
zstyle ':completion::complete:*' gain-privileges 1
autoload -Uz promptinit; promptinit
_comp_options+=(globdots) # Include hidden files.

autoload -U select-word-style
select-word-style bash
stty stop undef

setopt auto_cd
setopt COMPLETE_ALIASES
setopt inc_append_history
setopt share_history

# plugins
source $ZSHPATH/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $ZSHPATH/zsh-you-should-use/you-should-use.plugin.zsh

# load additional zsh alias/plugins
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f ~/go/bin/bin/jump ] && eval "$(~/go/bin/bin/jump shell zsh)"
[ -f "$XDG_CONFIG_HOME/aliasrc" ] && source "$XDG_CONFIG_HOME/aliasrc"
[ -f ~/.zshrc_local ] && source ~/.zshrc_local

# keybinds

# create a zkbd compatible hash;
# to add other keys to this hash, see: man 5 terminfo
typeset -g -A key

# partial command history search
autoload -Uz up-line-or-beginning-search down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search

[[ -n "${key[Up]}"   ]] && bindkey -- "${key[Up]}"   up-line-or-beginning-search
[[ -n "${key[Down]}" ]] && bindkey -- "${key[Down]}" down-line-or-beginning-search

# navigation
key[Control-Left]="${terminfo[kLFT5]}"
key[Control-Right]="${terminfo[kRIT5]}"

[[ -n "${key[Control-Left]}"  ]] && bindkey -- "${key[Control-Left]}"  backward-word
[[ -n "${key[Control-Right]}" ]] && bindkey -- "${key[Control-Right]}" forward-word

# emacs key mode
bindkey -e

# init prompt
prompt pure
