#!/bin/sh

# dependencies
# git jq bc jq vim docker xsel tar

# general

alias battery-status="upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep -E 'state|time\ to\ full|percentage'"
alias battery-powernow="awk '{print $1*10^-6 " W"}' /sys/class/power_supply/BAT0/power_now"
alias find-broken-symlinks-home="find ~/ -xtype l -print"
alias fonts="fc-list"
alias fonts-rebuild="fc-cache -f -v"
alias x-refresh-db="xrdb ~/.Xresources"
alias weather="curl 'wttr.in?format=2'"
alias keyboard-info="man 7 xkeyboard-config"
alias cpu-set-performance="sudo cpufreq-set -r -g performance"
alias cpu-set-powersave="sudo cpufreq-set -r -g powersave"

alias select-file="xsel -b <"
alias dir-size="du -sk * | sort -n"

alias untar="tar xvf"
alias untargz="tar zxvf"
alias untarxz="tar xf"
alias untarbz2="tar xjf"
alias ungz="gzip -d"
alias un7z="7za e"

alias zsh-debug="zprof > zprof-out.txt && less zprof-out.txt && rm zprof-out.txt"

# system

alias syslog-crit="sudo dmesg -w -l err,warn"
alias syslog="sudo dmesg -w"
alias ports="netstat -tulpn"
alias mountcol="mount | column -t"
alias getownip="curl ifconfig.me"
alias curl-json="curl --header 'Content-Type:application/json'"
alias calc="bc -ql"

# command line

alias vimz="fc"
alias json="jq"

# git

alias gco="git co"
alias gbd="git branch -D"

alias gcom="__git_checkout_main"
alias gcod="git co develop"

alias gaa="git add ."
alias gcm="git commit -m"
alias gcma="git add . && git commit -m"

alias gpf="git push --force-with-lease"
alias gpsup="__git_push_current_to_origin"
alias gptdm="git push --tags && git co develop && git push && git co master && git push"
alias gpla="git co develop && git pull && git co master && git pull"

alias gl="git pull"
alias gf="git fetch --all --verbose"
alias gfp="git fetch --all --prune --verbose"

alias glog="git log --oneline --decorate --graph"
alias gloga="git log --oneline --decorate --graph --all"
alias glol="git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'"
alias gt="git tag | sort -h"
alias gdesc="__git_latest_tag"

alias gb="git branch"
alias gbc="git branch --merged | egrep -v '(^\*|master|dev)' | xargs git branch -d && git pull --prune"

alias grs="git reset HEAD~ --soft"
alias grh="__git_reset_current_hard"

alias grt="git remote -v"

alias gsta="git stash -u"
alias gstl="git stash list"
alias gstp="git stash pop"

# git flow
alias gff="__git_flow_feature"
alias gfh="__git_flow_hotfix"
alias gfr="__git_flow_release"
alias gff="__git_flow_finish"

# list

if command -v exa >/dev/null; then
  alias ls="exa"
fi
alias la="ls -lah"

# npm

alias ni="npm install"
alias nig="npm install -g"
alias nid="npm install -D"
alias nlg="volta list all"
alias nr="npm run"
alias nrs="npm run start"
alias nin="npm init -y"
alias no="npm outdated"

alias nv="npm version --no-git-tag-version"

# kitty

alias icat="kitty +kitten icat"

# music

alias lofi="mpv --ytdl-format=93 \"https://www.youtube.com/watch?v=5qap5aO4i9A\" --no-video --really-quiet"
alias yt-audio="mpv --ytdl-format=251 $1 --no-video --really-quiet"
alias lofiv="vlc --open \"https://www.youtube.com/watch?v=5qap5aO4i9A\" &"

# python

alias pyfind='find . -name "*.py"'
alias pygrep='grep -nr --include="*.py"' # lookup text in python files
