#!/bin/sh

# dependencies
# git git-flow jq bc jq vim docker xsel tar

# general

alias battery-status="upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep -E 'state|time\ to\ full|percentage'"
alias docker-cleanup="echo 'Cleaning docker images older than 24h' && docker image prune -a --filter 'until=24h'"
alias find-broken-symlinks-home="find ~/ -xtype l -print"
alias fonts="fc-list"
alias fonts-rebuild="fc-cache -f -v"
alias x-refresh-db="xrdb ~/.Xresources"

alias select-file="xsel -b <"
alias dir-size="du -sk * | sort -n"

alias untar="tar xvf"
alias untargz="tar zxvf"
alias untarxz="tar xf"
alias untarbz2="tar xjf"
alias ungz="gzip -d"
alias un7z="7za e"

alias zsh-debug="zprof > zprof-out.txt && less zprof-out.txt && rm zprof-out.txt"

# cp, mv, rm

alias cp="cp -v"
alias mv='mv -v'
alias rm='rm -v'

# system

alias syslog-crit="sudo dmesg -w -l err,warn"
alias syslog="sudo dmesg -w"
alias ports="netstat -tulpn"
alias mountcol="mount | column -t"
alias getownip="curl ifconfig.me"
alias curl-json="curl --header 'Content-Type:application/json'"
alias calc="bc -ql"

# command line

alias vimz="fc"
alias json="jq"

# git

if command -v __git_fzf > /dev/null
then
  alias gco="__git_fzf 'checkout'"
  alias gbd="__git_fzf 'branch -D'"
else
  alias gco="git checkout"
  alias gbd="git branch -D"
fi

if command -v __git_checkout_main > /dev/null
then
  alias gcom="__git_checkout_main"
fi

alias gcod="git checkout develop"

alias gaa="git add ."
alias gcm="git commit -m"
alias gcma="git add . && git commit -m"

alias gp="git push"
if command -v __git_push_force_ask > /dev/null
then
  alias gpf="__git_push_force_ask"
else
  alias gpf="git push --force-with-lease"
fi

if command -v __git_push_current_to_origin > /dev/null
then
  alias gpsup="__git_push_current_to_origin"
fi
alias gptdm="git push --tags && git checkout develop && git push && git checkout master && git push"

alias gl="git pull"
alias gf="git fetch --all --verbose"
alias gfp="git fetch --all --prune --verbose"

alias glog="git log --oneline --decorate --graph"
alias gloga="git log --oneline --decorate --graph --all"
alias glol="git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'"
alias gst="git status"
alias gd="git diff"
alias gt="git tag | sort -h"
if command -v __git_latest_tag > /dev/null
then
  alias gdesc="__git_latest_tag"
else
  alias gdesc="git describe"
fi

alias gb="git branch"
alias gbc="git branch --merged | egrep -v '(^\*|master|dev)' | xargs git branch -d && git pull --prune"

alias grs="git reset HEAD~ --soft"
alias grh="__git_reset_current"

alias grv="git remote -v"

alias gsta="git stash -u"
alias gstl="git stash list"
alias gstp="git stash pop"

# git flow
if git flow config >/dev/null 2>&1
then
  alias gfin="git flow init -f -d -p 'feature/' -b 'bugfix/' -r 'release/' -x 'hotfix/' -s 'support/'"

  alias gffs="git flow feature start"

  if command -v __git_flow_hotfix_start > /dev/null
  then
    alias gfh="__git_flow_hotfix_start"
  else
    alias gdesc="git flow hotfix start"
  fi

  if command -v __git_flow_release_start > /dev/null
  then
    alias gfr="__git_flow_release_start"
  else
    alias gfr="git flow release start"
  fi

  if command -v __git_flow_finish > /dev/null
  then
    alias gff="__git_flow_finish"
  fi
fi

# list

if command -v exa > /dev/null
then
  alias ls="exa"
fi
alias la="ls -lah"

# npm

alias ni="npm install"
alias nig="npm install -g"
alias nid="npm install -D"
alias nlg="volta list all"
alias nr="npm run"
alias nrs="npm run start"
alias nin="npm init -y"

alias nv="npm version --no-git-tag-version"

# tmux

alias ta="tmux attach -t"
alias tad="tmux attach -d -t"
alias ts="tmux new-session -s"
alias tl="tmux list-sessions"
alias tksv="tmux kill-server"
alias tkss="tmux kill-session -t"

# music

alias lofi="mpv --ytdl-format=93 \"https://www.youtube.com/watch?v=5qap5aO4i9A\" --no-video --really-quiet"
alias yt-audio="mpv --ytdl-format=251 $1 --no-video --really-quiet"
alias lofiv="vlc --open \"https://www.youtube.com/watch?v=5qap5aO4i9A\" &"
