#!/bin/sh

# dependencies
# git jq bc jq vim docker xsel tar

# general

alias battery-status="upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep -E 'state|time\ to\ full|percentage'"
alias battery-powernow="awk '{print $1*10^-6 " W"}' /sys/class/power_supply/BAT0/power_now"
alias find-broken-symlinks-home="find ~/ -xtype l -print"
alias fonts="fc-list"
alias fonts-rebuild="fc-cache -f -v"
alias x-refresh-db="xrdb ~/.Xresources"
alias weather="curl 'wttr.in?format=2'"
alias keyboard-info="man 7 xkeyboard-config"
alias cpu-set-performance="sudo cpufreq-set -r -g performance"
alias cpu-set-powersave="sudo cpufreq-set -r -g powersave"

alias select-file="xsel -b <"
alias dir-size="du -sk * | sort -n"

alias untar="tar xvf"
alias untargz="tar zxvf"
alias untarxz="tar xf"
alias untarbz2="tar xjf"
alias ungz="gzip -d"
alias un7z="7za e"

alias zsh-debug="zprof > zprof-out.txt && less zprof-out.txt && rm zprof-out.txt"

# system

alias syslog-crit="sudo dmesg -w -l err,warn"
alias syslog="sudo dmesg -w"
alias ports="netstat -tulpn"
alias mountcol="mount | column -t"
alias getownip="curl ifconfig.me"
alias curl-json="curl --header 'Content-Type:application/json'"
alias calc="bc -ql"
alias network-active="nmcli device status"

# command line

alias vimz="fc"
alias json="jq"

# git

alias gptdm="git push --tags && git co develop && git push && git co master && git push"

# list

if command -v exa >/dev/null; then
  alias ls="exa"
fi
alias la="ls -lah"

# kitty

alias icat="kitty +kitten icat"

# python

alias pyfind='find . -name "*.py"'
alias pygrep='grep -nr --include="*.py"' # lookup text in python files
