#!/bin/sh

# xinitrc runs automatically when you run startx.

. ~/.xprofile

# Statusbar loop
while true; do
   xsetroot -name "$( date +"%F %R" )"
   sleep 1m  # Update time every minute
done &

ssh-agent startdwm
