
[[Snippets]]
  Description = "Save brewfile"
  Output = ""
  Tag = ["brew"]
  command = "brew bundle dump -gf"

[[Snippets]]
  Description = "Edit rice config files"
  Output = ""
  Tag = ["horiceon", "rice", "config"]
  command = "GIT_WORK_TREE=$HOME GIT_DIR=$HOME/code/horiceon code $HOME"

[[Snippets]]
  Description = "Delete merged branches"
  Output = ""
  Tag = ["git", "cleanup", "prune"]
  command = "git branch --merged | grep -E -v '(^\\*|master|dev|main)' | xargs git branch -d && git pull --prune"

[[Snippets]]
  Description = "Start docker with clean build"
  Output = ""
  Tag = ["docker", "docker-compose"]
  command = "docker compose up -d --force-recreate --build"

[[Snippets]]
  Description = "Boot docker with clean build, env and APP_VERSION"
  Output = ""
  Tag = ["docker", "docker-compose"]
  command = "APP_VERSION=$(git rev-parse --short HEAD) pnpm load-env -- docker compose up -d --force-recreate --build"

[[Snippets]]
  Description = "Migrate postgres DB"
  Output = ""
  Tag = ["DB", "postgres"]
  command = "cd apps/backend && pnpm db:migrate && cd -"
