[tools]
"bun" = "latest"
"deno" = "latest"
"dprint" = "latest"
"go:mvdan.cc/sh/v3/cmd/shfmt" = "latest"
"go" = "latest"
"node" = "latest"
"npm:@fission-ai/openspec" = "latest"
"npm:corepack" = "latest"
"npm:eslint" = "latest"
"npm:npq" = "latest"
"npm:prettier" = "latest"
"npm:sort-package-json" = "latest"
"npm:zx" = "latest"
# "python" = "3" # via brew
"rust" = "latest"
"uv" = "latest"

[settings]
always_keep_download = true
disable_backends = ["asdf", "pipx"]
experimental = true
idiomatic_version_file_enable_tools = [
  "node",
  "python",
  "go",
  "terraform",
  "yarn",
]
legacy_version_file = true

[settings.npm]
package_manager = "bun"

[hooks]
postinstall = 'npx corepack enable && corepack prepare'

[env]
_.path = ['{{config_root}}./node_modules/.bin']
